[package]
name = "automotive_can"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
vofa_core = { workspace = true }
can_types = { workspace = true }
transport_core = { workspace = true }
protocol_engine = { workspace = true }
protocol_can_bridge = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
async-trait = "0.1"
parking_lot = "0.12"
error = { workspace = true }